---
admin_user: kyleabenson
admin_password: P@ZZw0rd
ssh_pub_key: "{{lookup('file', 'path/to/file.txt')}}"
disk_size_gb: 10
desired_state: present #TODO, Add Absent Support
db_name: projectdb

#Azure Section
azure_resource_group: prodRG
azure_sql_server_name: "dbserver-{{azure_resource_group}}"
azure_network_name: myVirtualNetwork
azure_location: eastus
azure_lb_name: presentationLB
azure_image_details:
  offer: RHEL
  publisher: RedHat
  sku: 8.1
  version: latest

#GCP Section
gcp_project: kbenson-workspace
gcp_cred_kind: serviceaccount
gcp_cred_file: kbenson-workspace.json
gcp_source_image: "projects/rhel-cloud/global/images/rhel-8-v20200413"
gcp_region: us-east1
gcp_zone: "{{ gcp_region }}-b"
gcp_instance_group_name: simple-frontend
gcp_lb_name_prefix: frontend

#AWS Section