---
- name: Configure presentation layer hosts
  hosts: presentation
  become: true
  tasks:
    - name: Disable system level firewall
      service:
        name: firewalld
        state: stopped
        enabled: no

    - name: Install apache
      yum:
        name: httpd
        state: present
    
    - name: Start apache
      service:
        name: httpd
        state: started
        enabled: yes
    

